# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2e28760e81d19a6af60573ad257d5a5890c135ef1f2e95dde38610a90d43a75268ad3d9d598e54a8e665dafc51ceba5b2246902ab5c867ea77d3efd9041f6e8

test:
  secret_key_base: 80e8e884e30e533e0a19eebb99e94a71c331a0749d6a1e7b62ffa5e8ec10deae2df00a094edbda4b6d65933902748ccaf25fb1ec7bb0f1e9132975414ab3f72a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
